# Generated by Django 6.0.6 on 2026-08-02 04:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employees", "0003_employee_hold_until_employee_status_changed_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="reporting_manager",
            field=models.ForeignKey(
                blank=True,
                help_text="The senior / manager this employee reports to.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="team_members",
                to="employees.employee",
            ),
        ),
        migrations.CreateModel(
            name="PerformanceReview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "review_period_type",
                    models.CharField(
                        choices=[
                            ("monthly", "Monthly"),
                            ("quarterly", "Quarterly"),
                            ("half_yearly", "Half Yearly"),
                            ("annual", "Annual"),
                        ],
                        default="quarterly",
                        max_length=20,
                    ),
                ),
                ("period_start", models.DateField()),
                ("period_end", models.DateField()),
                (
                    "overall_rating",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (1, "1 - Needs Improvement"),
                            (2, "2 - Below Expectations"),
                            (3, "3 - Meets Expectations"),
                            (4, "4 - Exceeds Expectations"),
                            (5, "5 - Outstanding"),
                        ]
                    ),
                ),
                (
                    "goals_achieved",
                    models.TextField(
                        blank=True,
                        help_text="Key goals/targets achieved in this period.",
                    ),
                ),
                ("strengths", models.TextField(blank=True)),
                ("areas_of_improvement", models.TextField(blank=True)),
                ("reviewer_comments", models.TextField(blank=True)),
                (
                    "employee_comments",
                    models.TextField(
                        blank=True,
                        help_text="Employee's self-remarks / acknowledgement notes.",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("submitted", "Submitted"),
                            ("acknowledged", "Acknowledged by Employee"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="performance_reviews",
                        to="employees.employee",
                    ),
                ),
                (
                    "reviewer",
                    models.ForeignKey(
                        blank=True,
                        help_text="Usually the employee's reporting manager.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviews_given",
                        to="employees.employee",
                    ),
                ),
            ],
            options={
                "ordering": ["-period_end", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PerformanceGoal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "target_value",
                    models.CharField(
                        blank=True,
                        help_text="e.g. '95% attendance', '10 modules'",
                        max_length=100,
                    ),
                ),
                ("achieved_value", models.CharField(blank=True, max_length=100)),
                (
                    "weightage",
                    models.PositiveSmallIntegerField(
                        default=0,
                        help_text="% weight of this goal in the overall rating (0-100).",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("not_started", "Not Started"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("missed", "Missed"),
                        ],
                        default="not_started",
                        max_length=20,
                    ),
                ),
                (
                    "review",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="goals",
                        to="employees.performancereview",
                    ),
                ),
            ],
            options={
                "ordering": ["id"],
            },
        ),
    ]
