# Generated by Django 6.0.6 on 2026-08-06 16:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0003_shifttiming_attendancerecord_break_count_and_more"),
        ("employees", "0004_employee_reporting_manager_performancereview_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="shift",
            field=models.ForeignKey(
                blank=True,
                help_text="Assigned shift timing — controls the expected start time and late marking.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="employees",
                to="attendance.shifttiming",
            ),
        ),
        migrations.AddField(
            model_name="employee",
            name="standard_working_hours",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Working hours required per day for this employee. Leave blank to use the shift's default.",
                max_digits=4,
                null=True,
            ),
        ),
    ]
