# Generated by Django 6.0.6 on 2026-08-07 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employees", "0005_employee_shift_employee_standard_working_hours"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="biometric_id",
            field=models.CharField(
                blank=True,
                help_text="User ID / PIN configured for this employee on the fingerprint/biometric punch machine.",
                max_length=30,
                null=True,
                unique=True,
            ),
        ),
    ]
