# Generated by Django 6.0.6 on 2026-08-08 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employees", "0006_employee_biometric_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="aadhar_number",
            field=models.CharField(
                blank=True, help_text="12-digit Aadhaar number", max_length=20
            ),
        ),
        migrations.AddField(
            model_name="employee",
            name="bank_account_holder_name",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="employee",
            name="bank_account_number",
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name="employee",
            name="bank_ifsc_code",
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name="employee",
            name="bank_name",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="employee",
            name="pan_number",
            field=models.CharField(
                blank=True, help_text="10-character PAN", max_length=10
            ),
        ),
    ]
