# Generated by Django 6.0.6 on 2026-08-09 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employees", "0008_auditlog_sitesettings"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="is_primary_admin",
            field=models.BooleanField(
                default=False,
                help_text="Full Access Super Admin — can grant/revoke Super Admin access for others.",
            ),
        ),
    ]
