# Generated by Django 6.0.6 on 2026-08-09 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employees", "0009_employee_is_primary_admin"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="last_seen",
            field=models.DateTimeField(
                blank=True,
                help_text="Last time this employee's account made an authenticated request.",
                null=True,
            ),
        ),
    ]
