# Generated by Django 6.0.6 on 2026-08-16 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employees", "0012_announcement_notification_announcement"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="sitesettings",
            options={},
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="company_code",
            field=models.CharField(
                blank=True,
                help_text="Short internal code for the company, e.g. ABC001",
                max_length=20,
            ),
        ),
    ]
