# Generated by Django 6.0.6 on 2026-08-16 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("employees", "0013_alter_sitesettings_options_sitesettings_company_code"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="sitesettings",
            options={
                "verbose_name": "Site Settings",
                "verbose_name_plural": "Site Settings",
            },
        ),
    ]
