# Generated by Django 6.0.6 on 2026-07-27 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recruitment", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="candidate",
            options={"ordering": ["-applied_on"]},
        ),
        migrations.AlterModelOptions(
            name="jobopening",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AddField(
            model_name="interview",
            name="location",
            field=models.CharField(blank=True, default="Online", max_length=200),
        ),
        migrations.AddField(
            model_name="jobopening",
            name="employment_type",
            field=models.CharField(
                choices=[
                    ("full_time", "Full Time"),
                    ("part_time", "Part Time"),
                    ("contract", "Contract"),
                    ("intern", "Internship"),
                ],
                default="full_time",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="interview",
            name="rating",
            field=models.PositiveSmallIntegerField(
                blank=True,
                choices=[
                    (1, "⭐ Poor"),
                    (2, "⭐⭐ Below Average"),
                    (3, "⭐⭐⭐ Average"),
                    (4, "⭐⭐⭐⭐ Good"),
                    (5, "⭐⭐⭐⭐⭐ Excellent"),
                ],
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="jobopening",
            name="requirements",
            field=models.TextField(blank=True),
        ),
    ]
