# Generated by Django 6.0.6 on 2026-08-29 06:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("employees", "0014_alter_sitesettings_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExpenseClaim",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("travel", "Travel"),
                            ("food", "Food"),
                            ("cab", "Cab"),
                            ("hotel", "Hotel"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("expense_date", models.DateField()),
                ("description", models.TextField()),
                (
                    "bill",
                    models.FileField(
                        blank=True,
                        help_text="Scanned bill / receipt for this expense.",
                        null=True,
                        upload_to="expense_bills/",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending_manager", "Pending Manager Approval"),
                            ("pending_finance", "Pending Finance Approval"),
                            ("approved", "Approved"),
                            ("reimbursed", "Reimbursed"),
                            ("rejected", "Rejected"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending_manager",
                        max_length=20,
                    ),
                ),
                ("manager_reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("finance_reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("rejected_at", models.DateTimeField(blank=True, null=True)),
                ("rejection_reason", models.TextField(blank=True)),
                ("reimbursed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "transaction_reference",
                    models.CharField(
                        blank=True,
                        help_text="Bank transaction / UTR reference for the reimbursement payout.",
                        max_length=100,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="expense_claims",
                        to="employees.employee",
                    ),
                ),
                (
                    "finance_reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="finance_reviewed_expenses",
                        to="employees.employee",
                    ),
                ),
                (
                    "manager_reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="manager_reviewed_expenses",
                        to="employees.employee",
                    ),
                ),
                (
                    "reimbursed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reimbursed_expenses",
                        to="employees.employee",
                    ),
                ),
                (
                    "rejected_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="rejected_expenses",
                        to="employees.employee",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ExpenseComment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("submitted", "Submitted"),
                            ("manager_approved", "Approved by Manager"),
                            ("manager_rejected", "Rejected by Manager"),
                            ("finance_approved", "Approved by Finance"),
                            ("finance_rejected", "Rejected by Finance"),
                            ("reimbursed", "Marked Reimbursed"),
                            ("cancelled", "Cancelled"),
                            ("note", "Note"),
                        ],
                        max_length=20,
                    ),
                ),
                ("comment", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "by_employee",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="expense_comments",
                        to="employees.employee",
                    ),
                ),
                (
                    "expense",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="expenses.expenseclaim",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
    ]
