# Generated by Django 6.0.6 on 2026-08-09 07:51

import django.db.models.deletion
import tenants.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Tenant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Company ka naam, e.g. 'Acme Pvt Ltd'", max_length=255
                    ),
                ),
                (
                    "subdomain",
                    models.SlugField(
                        help_text="e.g. 'acme' -> acme.yourhrms.com. Local testing ke liye ?tenant=acme bhi chalega.",
                        unique=True,
                    ),
                ),
                (
                    "db_name",
                    models.CharField(editable=False, max_length=100, unique=True),
                ),
                (
                    "plan",
                    models.CharField(
                        choices=[
                            ("basic", "Basic"),
                            ("pro", "Pro"),
                            ("enterprise", "Enterprise"),
                        ],
                        default="basic",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("expired", "Expired"),
                            ("suspended", "Suspended"),
                        ],
                        default="suspended",
                        max_length=20,
                    ),
                ),
                (
                    "activation_key",
                    models.CharField(
                        default=tenants.models.generate_activation_key,
                        max_length=64,
                        unique=True,
                    ),
                ),
                (
                    "expiry_date",
                    models.DateField(
                        blank=True,
                        help_text="Is date ke baad dashboard lock ho jayega jab tak recharge na ho.",
                        null=True,
                    ),
                ),
                ("employee_limit", models.PositiveIntegerField(default=25)),
                (
                    "enabled_modules",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Kaunse modules is customer ke liye enabled hain, e.g. ['attendance','leaves']",
                    ),
                ),
                ("contact_email", models.EmailField(blank=True, max_length=254)),
                ("contact_phone", models.CharField(blank=True, max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="RechargeLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("days_added", models.PositiveIntegerField(default=30)),
                (
                    "payment_reference",
                    models.CharField(
                        blank=True,
                        help_text="Razorpay/Stripe payment ID, ya manual note",
                        max_length=100,
                    ),
                ),
                ("note", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recharges",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
