# Generated by Django 6.0.6 on 2026-08-09 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rechargelog",
            name="payment_reference",
            field=models.CharField(
                blank=True,
                help_text="Razorpay/Stripe payment ID, or a manual note",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="tenant",
            name="enabled_modules",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Which modules are enabled for this customer, e.g. ['attendance','leaves']",
            ),
        ),
        migrations.AlterField(
            model_name="tenant",
            name="expiry_date",
            field=models.DateField(
                blank=True,
                help_text="After this date the dashboard locks until the tenant is recharged.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="tenant",
            name="name",
            field=models.CharField(
                help_text="Company name, e.g. 'Acme Pvt Ltd'", max_length=255
            ),
        ),
        migrations.AlterField(
            model_name="tenant",
            name="subdomain",
            field=models.SlugField(
                help_text="e.g. 'acme' -> acme.yourhrms.com. For local testing, ?tenant=acme also works.",
                unique=True,
            ),
        ),
    ]
