# Generated by Django 6.0.6 on 2026-08-02 10:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="WellnessResource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("breathing", "Breathing Exercise"),
                            ("music", "Relaxing Music"),
                            ("video", "Relaxation Video"),
                            ("quote", "Motivational Quote"),
                            ("tip", "Wellness Tip"),
                            ("game", "Mind Game / Puzzle"),
                        ],
                        default="tip",
                        max_length=20,
                    ),
                ),
                (
                    "resource_url",
                    models.URLField(
                        blank=True,
                        help_text="External link — YouTube video, Spotify playlist, article, etc. (optional)",
                    ),
                ),
                (
                    "duration_minutes",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        help_text="Approx. time to complete/listen (optional)",
                        null=True,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
