# Generated by Django 6.0.6 on 2026-07-24 15:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employees", "0002_employeerole_project"),
        ("leaves", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="LeaveComment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("comment", models.TextField()),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("comment", "Comment"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("forwarded", "Forwarded"),
                        ],
                        default="comment",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "commented_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="employees.employee",
                    ),
                ),
                (
                    "leave",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="leaves.leaverequest",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
    ]
