# Generated by Django 6.0.6 on 2026-08-09 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leaves", "0002_leavecomment"),
    ]

    operations = [
        migrations.AddField(
            model_name="leavebalance",
            name="last_accrual_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
