# Generated by Django 6.0.6 on 2026-08-09 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leaves", "0003_leavebalance_last_accrual_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="leaverequest",
            name="half_day_session",
            field=models.CharField(
                blank=True,
                choices=[("first_half", "First Half"), ("second_half", "Second Half")],
                max_length=12,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="leaverequest",
            name="is_half_day",
            field=models.BooleanField(default=False),
        ),
    ]
