# Generated by Django 6.0.6 on 2026-09-06 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leaves", "0004_leaverequest_half_day_session_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="leavetype",
            name="is_short_leave",
            field=models.BooleanField(
                default=False,
                help_text="Mark this leave type as a 'Short Leave' (a few hours off, not a full day). When a request of this type is approved, the day is recorded in Attendance as 'Short Leave' and a partial (not full-day) deduction is applied in payroll, instead of being skipped like a normal full-day leave.",
            ),
        ),
    ]
