# Generated by Django 6.0.6 on 2026-08-01 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payroll", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="payslip",
            name="tax_regime",
            field=models.CharField(
                choices=[("new", "New Regime"), ("old", "Old Regime")],
                default="new",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="salarystructure",
            name="deduction_80c",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Section 80C investments (PF, ELSS, LIC, etc.) — applicable under Old Regime only.",
                max_digits=10,
            ),
        ),
        migrations.AddField(
            model_name="salarystructure",
            name="deduction_80d",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Section 80D health insurance premium — applicable under Old Regime only.",
                max_digits=10,
            ),
        ),
        migrations.AddField(
            model_name="salarystructure",
            name="tax_regime",
            field=models.CharField(
                choices=[("new", "New Regime"), ("old", "Old Regime")],
                default="new",
                max_length=10,
            ),
        ),
    ]
