# Generated by Django 6.0.6 on 2026-08-18 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payroll", "0002_payslip_tax_regime_salarystructure_deduction_80c_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="payslip",
            name="bonus",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="payslip",
            name="esi_deduction",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Employee State Insurance contribution (0.75% of gross, only if gross <= ₹21,000/month).",
                max_digits=10,
            ),
        ),
        migrations.AddField(
            model_name="payslip",
            name="incentive",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="payslip",
            name="overtime_amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="payslip",
            name="overtime_hours",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Total overtime hours, auto-computed from Attendance working_hours beyond standard shift hours.",
                max_digits=6,
            ),
        ),
        migrations.AddField(
            model_name="payslip",
            name="payable_days",
            field=models.DecimalField(
                decimal_places=1,
                default=0,
                help_text="Total days in the pay period, used as the base for per-day salary.",
                max_digits=4,
            ),
        ),
        migrations.AddField(
            model_name="payslip",
            name="present_days",
            field=models.DecimalField(decimal_places=1, default=0, max_digits=4),
        ),
        migrations.AddField(
            model_name="salarystructure",
            name="overtime_rate_per_hour",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Amount paid per hour of overtime worked beyond standard working hours.",
                max_digits=10,
            ),
        ),
        migrations.AddField(
            model_name="salarystructure",
            name="standard_bonus",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Recurring monthly bonus (if any) added to every payslip by default.",
                max_digits=10,
            ),
        ),
        migrations.AddField(
            model_name="salarystructure",
            name="standard_incentive",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Recurring monthly incentive (if any) added to every payslip by default.",
                max_digits=10,
            ),
        ),
        migrations.AlterField(
            model_name="payslip",
            name="lop_days",
            field=models.DecimalField(
                decimal_places=1,
                default=0,
                help_text="Loss-of-pay days, auto-computed from Attendance (absent days without approved leave).",
                max_digits=4,
            ),
        ),
    ]
