# Generated by Django 6.0.6 on 2026-08-29 16:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employees", "0014_alter_sitesettings_options"),
        ("payroll", "0003_payslip_bonus_payslip_esi_deduction_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="payslip",
            name="approved_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="payslip",
            name="approved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="approved_payslips",
                to="employees.employee",
            ),
        ),
        migrations.AddField(
            model_name="payslip",
            name="is_approved",
            field=models.BooleanField(
                default=False,
                help_text="HR/Super Admin approval to release this payslip for employee print/download.",
            ),
        ),
    ]
