# Generated by Django 6.0.6 on 2026-08-06 16:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0002_workfromhomerequest"),
        ("employees", "0004_employee_reporting_manager_performancereview_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ShiftTiming",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
                (
                    "start_time",
                    models.TimeField(help_text="Shift start time, e.g. 09:00"),
                ),
                ("end_time", models.TimeField(help_text="Shift end time, e.g. 18:00")),
                (
                    "working_hours",
                    models.DecimalField(
                        decimal_places=2,
                        default=8.0,
                        help_text="Expected/standard working hours per day for this shift.",
                        max_digits=4,
                    ),
                ),
                (
                    "grace_minutes",
                    models.PositiveIntegerField(
                        default=10,
                        help_text="Minutes allowed after start_time before a punch-in is marked Late.",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["start_time"],
            },
        ),
        migrations.AddField(
            model_name="attendancerecord",
            name="break_count",
            field=models.PositiveIntegerField(
                default=0, help_text="Number of breaks taken on this date."
            ),
        ),
        migrations.AddField(
            model_name="attendancerecord",
            name="is_punched_in",
            field=models.BooleanField(
                default=False,
                help_text="True while the employee is currently punched in.",
            ),
        ),
        migrations.AddField(
            model_name="attendancerecord",
            name="total_break_minutes",
            field=models.PositiveIntegerField(
                default=0, help_text="Total break time in minutes."
            ),
        ),
        migrations.AlterField(
            model_name="attendancerecord",
            name="check_in",
            field=models.TimeField(
                blank=True, help_text="First punch-in of the day.", null=True
            ),
        ),
        migrations.AlterField(
            model_name="attendancerecord",
            name="check_out",
            field=models.TimeField(
                blank=True, help_text="Last punch-out of the day.", null=True
            ),
        ),
        migrations.AlterField(
            model_name="attendancerecord",
            name="working_hours",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Net working hours = (last punch-out - first punch-in) - total break time.",
                max_digits=4,
                null=True,
            ),
        ),
        migrations.CreateModel(
            name="PunchLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date",
                    models.DateField(
                        help_text="Attendance date this punch belongs to."
                    ),
                ),
                (
                    "punch_type",
                    models.CharField(
                        choices=[("in", "Punch In"), ("out", "Punch Out")], max_length=3
                    ),
                ),
                ("timestamp", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="punch_logs",
                        to="employees.employee",
                    ),
                ),
            ],
            options={
                "ordering": ["timestamp"],
            },
        ),
    ]
