# Generated by Django 6.0.6 on 2026-08-07 17:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0003_shifttiming_attendancerecord_break_count_and_more"),
        ("employees", "0006_employee_biometric_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="BiometricDevice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("serial_number", models.CharField(max_length=50, unique=True)),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        help_text="e.g. 'Main Gate', 'Office Entrance'",
                        max_length=100,
                    ),
                ),
                ("location", models.CharField(blank=True, max_length=100)),
                ("last_seen_at", models.DateTimeField(blank=True, null=True)),
                ("last_ip", models.GenericIPAddressField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-last_seen_at"],
            },
        ),
        migrations.AddField(
            model_name="punchlog",
            name="device_serial",
            field=models.CharField(blank=True, default="", max_length=50),
        ),
        migrations.AddField(
            model_name="punchlog",
            name="source",
            field=models.CharField(
                choices=[("web", "Web / App"), ("device", "Biometric Device")],
                default="web",
                max_length=10,
            ),
        ),
        migrations.CreateModel(
            name="BiometricRawLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "device_user_id",
                    models.CharField(
                        help_text="Raw PIN/User ID from the device.", max_length=30
                    ),
                ),
                ("device_serial", models.CharField(blank=True, max_length=50)),
                ("timestamp", models.DateTimeField()),
                ("raw_line", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "employee",
                    models.ForeignKey(
                        blank=True,
                        help_text="Matched employee, if this device_user_id was mapped at the time of push.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="biometric_raw_logs",
                        to="employees.employee",
                    ),
                ),
                (
                    "punch_log",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="raw_source",
                        to="attendance.punchlog",
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
            },
        ),
    ]
