# Generated by Django 6.0.6 on 2026-08-13 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0005_faceencoding"),
    ]

    operations = [
        migrations.AddField(
            model_name="punchlog",
            name="latitude",
            field=models.DecimalField(
                blank=True,
                decimal_places=6,
                help_text="Browser geolocation latitude captured at the moment of punch (web punches only).",
                max_digits=9,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="punchlog",
            name="location_name",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Human-readable address resolved from lat/lng (reverse geocoded in the browser).",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="punchlog",
            name="longitude",
            field=models.DecimalField(
                blank=True,
                decimal_places=6,
                help_text="Browser geolocation longitude captured at the moment of punch (web punches only).",
                max_digits=9,
                null=True,
            ),
        ),
    ]
