# Generated by Django 6.0.6 on 2026-08-29 16:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0006_punchlog_latitude_punchlog_location_name_and_more"),
        ("employees", "0014_alter_sitesettings_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="AttendanceDispute",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(help_text="The date being disputed.")),
                (
                    "current_status",
                    models.CharField(
                        blank=True,
                        help_text="What the record showed at the time of raising the claim.",
                        max_length=20,
                    ),
                ),
                (
                    "claimed_status",
                    models.CharField(
                        choices=[
                            ("present", "Present"),
                            ("absent", "Absent"),
                            ("half_day", "Half Day"),
                            ("late", "Late"),
                            ("work_from_home", "Work From Home"),
                            ("holiday", "Holiday"),
                        ],
                        help_text="What the employee says the correct status should be.",
                        max_length=20,
                    ),
                ),
                (
                    "reason",
                    models.TextField(help_text="Employee's explanation for the claim."),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("review_note", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "attendance_record",
                    models.ForeignKey(
                        blank=True,
                        help_text="Existing attendance record for this date, if any.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="disputes",
                        to="attendance.attendancerecord",
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attendance_disputes",
                        to="employees.employee",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_disputes",
                        to="employees.employee",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
