# Generated by Django 6.0.6 on 2026-09-06 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0008_alter_attendancedispute_claimed_status_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attendancedispute",
            name="claimed_status",
            field=models.CharField(
                choices=[
                    ("present", "Present"),
                    ("absent", "Absent"),
                    ("half_day", "Half Day"),
                    ("late", "Late"),
                    ("work_from_home", "Work From Home"),
                    ("holiday", "Holiday"),
                    ("short_leave", "Short Leave"),
                    ("PA", "PA (Incomplete Hours, No Leave — Full Day Deducted)"),
                ],
                help_text="What the employee says the correct status should be.",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="attendancerecord",
            name="status",
            field=models.CharField(
                choices=[
                    ("present", "Present"),
                    ("absent", "Absent"),
                    ("half_day", "Half Day"),
                    ("late", "Late"),
                    ("work_from_home", "Work From Home"),
                    ("holiday", "Holiday"),
                    ("short_leave", "Short Leave"),
                    ("PA", "PA (Incomplete Hours, No Leave — Full Day Deducted)"),
                ],
                default="present",
                max_length=20,
            ),
        ),
    ]
